<?php
require_once 'config.php'; require_once 'functions.php'; requireLogin(); requirePermission($pdo, 'payments.manage');
if($_SERVER['REQUEST_METHOD']==='POST'){
 verifyCsrf();$studentId=(int)($_POST['student_id']??0);$title=trim($_POST['title']??'القسط الدراسي');$total=(float)($_POST['total_amount']??0);$paid=(float)($_POST['paid_amount']??0);$due=$_POST['due_date']??'';$note=trim($_POST['note']??'');
 $status=$paid >= $total && $total>0 ? 'paid' : ($paid>0 ? 'partial' : 'pending'); if($due && $due<date('Y-m-d') && $status!=='paid')$status='overdue';
 if($paid<0||$paid>$total||!validDate($due)||mb_strlen($title)>150||mb_strlen($note)>255){flash('error','تحقق من المبلغ والتاريخ وبيانات القسط.');redirect('installments.php');}
 if($studentId&&$total>0&&$due){$check=$pdo->prepare('SELECT id FROM students WHERE id=:id AND status="active"');$check->execute(['id'=>$studentId]);if(!$check->fetchColumn()){flash('error','الطالب المحدد غير موجود أو غير نشط.');redirect('installments.php');}$st=$pdo->prepare('INSERT INTO installments(student_id,title,total_amount,paid_amount,due_date,status,note) VALUES(:student,:title,:total,:paid,:due,:status,:note)');$st->execute(['student'=>$studentId,'title'=>$title,'total'=>$total,'paid'=>$paid,'due'=>$due,'status'=>$status,'note'=>$note?:null]);logAudit($pdo,'إضافة قسط','installment',(int)$pdo->lastInsertId(),'الإجمالي: '.formatMoney($total));flash('success','تم تسجيل القسط واحتسابه في التنبيهات.');}else{flash('error','اختر الطالب وأدخل المبلغ وتاريخ الاستحقاق.');}redirect('installments.php');
}
$students=$pdo->query("SELECT id,full_name,student_code FROM students WHERE status='active' ORDER BY full_name")->fetchAll();
$items=$pdo->query("SELECT i.*,s.full_name,s.student_code,(i.total_amount-i.paid_amount) AS balance FROM installments i JOIN students s ON s.id=i.student_id ORDER BY FIELD(i.status,'overdue','pending','partial','paid'), i.due_date ASC")->fetchAll();
$pageTitle='الأقساط والتنبيهات';require 'partials/header.php';$labels=['pending'=>'مستحق','partial'=>'مدفوع جزئيًا','paid'=>'مسدد','overdue'=>'متأخر'];
?>
<div class="page-heading"><div><p class="eyebrow">المتابعة المالية</p><h1>الأقساط والتنبيهات</h1><p>تابع الأقساط المستحقة والمتأخرة لكل طالب.</p></div></div>
<section class="panel"><div class="panel-header"><h2>إضافة قسط جديد</h2></div><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrfToken()) ?>"><div class="form-grid"><div class="form-group"><label>الطالب</label><select class="form-control" name="student_id" required><option value="">اختر الطالب</option><?php foreach($students as $s): ?><option value="<?= (int)$s['id'] ?>"><?= e($s['full_name']) ?> — <?= e($s['student_code']) ?></option><?php endforeach;?></select></div><div class="form-group"><label>اسم القسط</label><input class="form-control" name="title" value="القسط الدراسي"></div><div class="form-group"><label>إجمالي المبلغ</label><input class="form-control" type="number" min="1" step="0.01" name="total_amount" required></div><div class="form-group"><label>المدفوع حاليًا</label><input class="form-control" type="number" min="0" step="0.01" name="paid_amount" value="0"></div><div class="form-group"><label>تاريخ الاستحقاق</label><input class="form-control" type="date" name="due_date" required></div><div class="form-group"><label>ملاحظة</label><input class="form-control" name="note"></div></div><div class="form-actions"><button class="btn btn-primary">حفظ القسط</button></div></form></section>
<section class="panel"><div class="panel-header"><h2>متابعة الأقساط</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>الطالب</th><th>القسط</th><th>الإجمالي</th><th>المتبقي</th><th>الاستحقاق</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody><?php foreach($items as $item): ?><tr><td class="student-name"><?= e($item['full_name']) ?><small class="student-code"><?= e($item['student_code']) ?></small></td><td><?= e($item['title']) ?></td><td><?= formatMoney($item['total_amount']) ?></td><td><?= formatMoney($item['balance']) ?></td><td><?= e($item['due_date']) ?></td><td><span class="badge <?= $item['status']==='overdue'?'badge-danger':($item['status']==='paid'?'badge-success':'badge-blue') ?>"><?= e($labels[$item['status']]) ?></span></td><td><?php if($item['status']!=='paid'):?><a class="btn btn-light btn-sm" href="installment_pay.php?id=<?=(int)$item['id']?>">تسجيل دفعة</a><?php endif;?></td></tr><?php endforeach;?><?php if(!$items):?><tr><td class="empty" colspan="7">لا توجد أقساط مسجلة.</td></tr><?php endif;?></tbody></table></div></section>
<?php require 'partials/footer.php'; ?>
