<?php
require_once 'config.php'; require_once 'functions.php'; requireLogin(); requirePermission($pdo, 'subjects.view');
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)?:0;$subject=null;if($id){$st=$pdo->prepare('SELECT * FROM subjects WHERE id=:id');$st->execute(['id'=>$id]);$subject=$st->fetch();}
if($_SERVER['REQUEST_METHOD']==='POST'){
 requirePermission($pdo,'subjects.manage'); verifyCsrf();
 $name=trim($_POST['name']??'');$code=trim($_POST['code']??'');$stage=trim($_POST['stage']??'');
 $description=trim($_POST['description']??'');$weekly=(int)($_POST['weekly_periods']??2);
 if($name===''||mb_strlen($name)>120||mb_strlen($code)>30||mb_strlen($description)>255||$weekly<1||$weekly>20){flash('error','تحقق من اسم المادة والرمز وعدد الحصص الأسبوعية.');redirect($id?"subjects.php?id=$id":'subjects.php?action=create');}
 try{
  if($id){$st=$pdo->prepare('UPDATE subjects SET name=:name,code=:code,stage=:stage,description=:description,weekly_periods=:weekly WHERE id=:id');$st->execute(['name'=>$name,'code'=>$code?:null,'stage'=>$stage?:null,'description'=>$description?:null,'weekly'=>$weekly,'id'=>$id]);logAudit($pdo,'تحديث مادة','subject',$id,'تم تعديل المادة');flash('success','تم تحديث المادة.');}
  else{$st=$pdo->prepare('INSERT INTO subjects(name,code,stage,description,weekly_periods) VALUES(:name,:code,:stage,:description,:weekly)');$st->execute(['name'=>$name,'code'=>$code?:null,'stage'=>$stage?:null,'description'=>$description?:null,'weekly'=>$weekly]);$new=(int)$pdo->lastInsertId();logAudit($pdo,'إضافة مادة','subject',$new,'تم إنشاء المادة');flash('success','تمت إضافة المادة.');}
 }catch(PDOException $e){flash('error','تعذر حفظ المادة. قد يكون رمز المادة مستخدمًا مسبقًا.');}
 redirect('subjects.php');
}
$subjects=$pdo->query('SELECT * FROM subjects ORDER BY name')->fetchAll();$pageTitle='المواد الدراسية';require 'partials/header.php';
?>
<div class="page-heading"><div><p class="eyebrow">التنظيم الأكاديمي</p><h1>المواد الدراسية</h1><p>أنشئ المواد التي تريد عرضها في السجل والتقارير.</p></div><div class="actions"><a class="btn btn-primary" href="subjects.php?action=create">+ إضافة مادة</a></div></div>
<?php if($id||($_GET['action']??'')==='create'):?><section class="panel"><div class="panel-header"><h2><?= $id?'تعديل المادة':'إضافة مادة دراسية'?></h2><a href="subjects.php">إلغاء</a></div><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrfToken())?>"><div class="form-grid"><div class="form-group"><label>اسم المادة *</label><input class="form-control" name="name" required value="<?=e($subject['name']??'')?>" placeholder="مثال: الرياضيات"></div><div class="form-group"><label>الرمز</label><input class="form-control" name="code" value="<?=e($subject['code']??'')?>" dir="ltr" placeholder="MATH-01"></div><div class="form-group"><label>المرحلة</label><select class="form-control" name="stage"><option value="">جميع المراحل</option><?php foreach(['رياض الأطفال','المرحلة الابتدائية','المرحلة المتوسطة','المرحلة الثانوية'] as $v):?><option <?=$v===($subject['stage']??'')?'selected':''?>><?=e($v)?></option><?php endforeach;?></select></div><div class="form-group"><label>الحصص الأسبوعية</label><input class="form-control" type="number" name="weekly_periods" min="1" max="20" value="<?=e($subject['weekly_periods']??2)?>"></div><div class="form-group full"><label>الوصف</label><input class="form-control" name="description" value="<?=e($subject['description']??'')?>"></div></div><div class="form-actions"><button class="btn btn-primary">حفظ المادة</button></div></form></section><?php endif;?>
<section class="panel"><div class="panel-header"><h2>سجل المواد</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>المادة</th><th>المرحلة</th><th>الرمز</th><th>الحصص</th><th>الوصف</th><th></th></tr></thead><tbody><?php foreach($subjects as $item):?><tr><td class="student-name"><?=e($item['name'])?></td><td><?=e($item['stage']?:'جميع المراحل')?></td><td><?=e($item['code']?:'-')?></td><td><?=e($item['weekly_periods']??2)?></td><td><?=e($item['description']?:'-')?></td><td><a class="btn btn-light btn-sm" href="subjects.php?id=<?=(int)$item['id']?>">تعديل</a></td></tr><?php endforeach;?><?php if(!$subjects):?><tr><td class="empty" colspan="6">لا توجد مواد.</td></tr><?php endif;?></tbody></table></div></section>
<?php require 'partials/footer.php';?>
